In [1]:
import pandas as pd
import pickle
import duckdb

SCRATCH_DIR = "/scratch/siads696f23_class_root/siads696f23_class/psollars"

# For local dev
SCRATCH_DIR = "./../data"

In [2]:
query = f"SELECT * FROM '{SCRATCH_DIR}/bts_faa_coords.parquet' ORDER BY RANDOM() LIMIT 100;"

bts_faa_coords_sample = duckdb.query(query).df()

bts_faa_coords_sample.to_csv("bts_faa_coords_sample.csv")

bts_faa_coords_sample.head()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginCityMarketID,...,TC-DATA-HOLDER,faa_registration_origin,Origin_DISPLAY_AIRPORT_NAME,Origin_DISPLAY_AIRPORT_CITY_NAME_FULL,Origin_LATITUDE,Origin_LONGITUDE,Dest_DISPLAY_AIRPORT_NAME,Dest_DISPLAY_AIRPORT_CITY_NAME_FULL,Dest_LATITUDE,Dest_LONGITUDE
0,2018,4,12,12,3,2018-12-12 00:00:00,AA,155UW,1670,30693,...,AIRBUS SAS ...,2023.0,Nashville International,"Nashville, TN",36.124444,-86.678056,Charlotte Douglas International,"Charlotte, NC",35.213611,-80.949167
1,2017,1,2,20,1,2017-02-20 00:00:00,B6,805JB,1512,31714,...,AIRBUS SAS ...,2023.0,Southwest Florida International,"Fort Myers, FL",26.536111,-81.755278,Newark Liberty International,"Newark, NJ",40.692500,-74.168611
2,2022,3,8,18,4,2022-08-18 00:00:00,WN,8724J,693,30721,...,...,2023.0,Rhode Island Tf Green International,"Providence, RI",41.722222,-71.427778,Orlando International,"Orlando, FL",28.429444,-81.308889
3,2021,3,7,30,5,2021-07-30 00:00:00,UA,26215,220,30325,...,...,2023.0,Denver International,"Denver, CO",39.861667,-104.673056,Salt Lake City International,"Salt Lake City, UT",40.788333,-111.977778
4,2018,1,2,26,1,2018-02-26 00:00:00,WN,8711Q,438,33195,...,...,2023.0,Tampa International,"Tampa, FL",27.975556,-82.533333,Chicago Midway International,"Chicago, IL",41.785833,-87.752500

In [3]:
query = f"SELECT * FROM '{SCRATCH_DIR}/all_features_2019.parquet' LIMIT 100000;"

all_features_2019_df = duckdb.query(query).df().drop("__index_level_0__", axis="columns")

all_features_2019_sample = all_features_2019_df.sample(100, random_state=42)

all_features_2019_sample.to_csv("all_features_2019_sample.csv")

all_features_2019_sample.head()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginCityMarketID,...,TC-DATA-HOLDER,faa_registration_origin,Origin_DISPLAY_AIRPORT_NAME,Origin_DISPLAY_AIRPORT_CITY_NAME_FULL,Origin_LATITUDE,Origin_LONGITUDE,Dest_DISPLAY_AIRPORT_NAME,Dest_DISPLAY_AIRPORT_CITY_NAME_FULL,Dest_LATITUDE,Dest_LONGITUDE
75721,2019,1,1,30,3,2019-01-30 00:00:00,AS,402AS,183,30559,...,...,2023.0,Seattle/Tacoma International,"Seattle, WA",47.450000,-122.311667,Ted Stevens Anchorage International,"Anchorage, AK",61.174167,-149.998056
80184,2019,1,1,6,7,2019-01-06 00:00:00,AS,549AS,723,30194,...,...,2023.0,Dallas/Fort Worth International,"Dallas/Fort Worth, TX",32.897222,-97.037778,Seattle/Tacoma International,"Seattle, WA",47.450000,-122.311667
19864,2019,1,1,29,2,2019-01-29 00:00:00,OO,641CA,3568,34614,...,...,2023.0,Salt Lake City International,"Salt Lake City, UT",40.788333,-111.977778,Tri Cities,"Pasco/Kennewick/Richland, WA",46.264722,-119.118889
76699,2019,1,1,31,4,2019-01-31 00:00:00,AS,839VA,1071,30852,...,AIRBUS SAS ...,2023.0,Washington Dulles International,"Washington, DC",38.947500,-77.460000,San Francisco International,"San Francisco, CA",37.618889,-122.375556
92991,2019,1,1,22,2,2019-01-22 00:00:00,9E,341PQ,5073,34100,...,...,2023.0,Philadelphia International,"Philadelphia, PA",39.871944,-75.240556,Logan International,"Boston, MA",42.363056,-71.006389

In [4]:
query = f"SELECT * FROM '{SCRATCH_DIR}/top_airline_airport_2019.parquet' LIMIT 100000;"

top_airline_airport_2019_df = duckdb.query(query).df().drop("__index_level_0__", axis="columns")

top_airline_airport_2019_sample = top_airline_airport_2019_df.sample(100, random_state=42)

top_airline_airport_2019_sample.to_csv("top_airline_airport_2019_sample.csv")

top_airline_airport_2019_sample.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginCityMarketID,...,faa_registration_origin,Origin_DISPLAY_AIRPORT_NAME,Origin_DISPLAY_AIRPORT_CITY_NAME_FULL,Origin_LATITUDE,Origin_LONGITUDE,Dest_DISPLAY_AIRPORT_NAME,Dest_DISPLAY_AIRPORT_CITY_NAME_FULL,Dest_LATITUDE,Dest_LONGITUDE,delayed
75721,2019,1,1,26,6,2019-01-26 00:00:00,WN,7839A,3699,32211,...,2023.0,Harry Reid International,"Las Vegas, NV",36.080000,-115.152222,Tucson International,"Tucson, AZ",32.116111,-110.941111,False
80184,2019,1,1,3,4,2019-01-03 00:00:00,WN,498WN,1860,32457,...,2023.0,San Francisco International,"San Francisco, CA",37.618889,-122.375556,Phoenix Sky Harbor International,"Phoenix, AZ",33.434167,-112.011667,False
19864,2019,1,1,2,3,2019-01-02 00:00:00,AA,137AA,553,31057,...,2023.0,Charlotte Douglas International,"Charlotte, NC",35.213611,-80.949167,Dallas/Fort Worth International,"Dallas/Fort Worth, TX",32.897222,-97.037778,False
76699,2019,1,1,27,7,2019-01-27 00:00:00,WN,7832A,2614,30325,...,2023.0,Denver International,"Denver, CO",39.861667,-104.673056,Will Rogers World,"Oklahoma City, OK",35.393056,-97.600833,False
92991,2019,1,1,6,7,2019-01-06 00:00:00,WN,8535S,5539,31423,...,2023.0,Des Moines International,"Des Moines, IA",41.534167,-93.657778,Phoenix Sky Harbor International,"Phoenix, AZ",33.434167,-112.011667,False

In [6]:
query = f"SELECT * FROM '{SCRATCH_DIR}/top_airline_airport_consolidated_features_2019.parquet' LIMIT 100000;"

consolidated_features_df = duckdb.query(query).df().drop("__index_level_0__", axis="columns")

consolidated_features_sample = consolidated_features_df.sample(100, random_state=42)

consolidated_features_sample.to_csv("top_airline_airport_consolidated_features_2019.csv")

consolidated_features_sample.head()

,Quarter,Month,DayofMonth,DayOfWeek,CRSDepTime,CRSArrTime,CRSElapsedTime,Distance,DistanceGroup,year_of_manufacture,...,aircraft_type,aircraft_manufacturer,aircraft_model,DepDel15,ArrDel15,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
75721,1,1,28,1,1805,2010,185,1044,5,2013,...,5,BOEING,737-8H4,0,0,0,0,0,0,0
80184,1,1,12,6,1800,2010,130,602,3,2011,...,5,BOEING,737-7H4,0,0,0,0,0,0,0
19864,1,1,2,3,1013,1607,234,1814,8,1999,...,4,AIRBUS,A320-232,0,0,0,0,0,0,0
76699,1,1,3,4,1950,2340,170,1256,6,2001,...,5,BOEING,737-7H4,0,0,0,0,0,0,0
92991,1,1,15,2,0745,0950,125,602,3,2014,...,5,BOEING,737-8H4,0,0,0,0,0,0,0